### PR TITLE
Fixup parsing of KafkaCrypto configuration file parameters. This fixes

### PR DESCRIPTION
**Pull request by tmcqueen-materials**
the root cause of the behavior worked around by commit https://github.com/tmcqueen-materials/kafkacrypto/commit/ec00565d2a2e4d35be01afacd46a8e5cc54b0650 and makes sure all KafkaCrypto configuration parameters are appropriately applied, e.g. log_level for KafkaCrypto logging.

### CODE REVIEW

**Comment by eminizer** [comment]
Hi @tmcqueen-materials,

Thanks for the catch and update! Before I merge this, may I suggest one edit to the KafkaCrypto code that now currently messes with some formatting on the OpenMSIStream (or other endpoint) ends?

Currently, Initializing a KafkaCryptoStore [includes a call to logging.basicConfig](https://github.com/tmcqueen-materials/kafkacrypto/blob/master/kafkacrypto/kafkacryptostore.py#L30), which will edit the configuration of any loggers in any programs after the KafkaCryptoStore is initialized. That breaks the format of all of the OpenMSIStream logging messages after the call is made. Would it be possible to edit just the kafkacrypto logger at that point in a new version of kafkacrypto, or otherwise reliably undo the change in the OpenMSIStream code? Happy to workshop alternatives to this approach, but if you do end up lightly editing the KafkaCrypto code could you also please update this PR with an edit to the required KafkaCrypto version in the setup.py file?

I also flipped a switch on CircleCI that should now automatically run tests for PRs from forks, so you should now be able to see test results on these PR pages, but we'll see if that's the case if there are any more updates....

Thank you!!!

**Comment by tmcqueen-materials** [comment]
@eminizer : I think I can certainly add it as an option -- the present functionality of KafkaCryptoStore is because some other downstream consumers want to use log_level to control logging across the entire package. But in an update I can make KafkaCryptoStore take another optional parameter that determines whether the basicConfig part is executed or not. I'd like to bundle that fix with the python 3.12 compatibility fix into the next release, but that is blocking on [kafka-python](https://github.com/dpkp/kafka-python/issues/2408). So if that goes too far in January I'll cut a new KafkaCrypto release with just the KafkaCryptoStore change. This PR will then need to be updated to pass that new optional parameter. Thanks!

**Comment by eminizer** [comment]
@tmcqueen-materials that sounds good to me! Let me know if I can be of any help in the meantime.

**Comment by tmcqueen-materials** [comment]
@eminizer : OK, at this point this should be good to go. Since this properly fixes parsing of the kafkacrypto configuration, the tests do need to be updated so that, e.g., the kafkacrypto file doesn't set a ca file location that is different than the main one and cause the CI to fail. This is the cause of all of the remaining CI failures. If other things crop up when that part of the tests are fixed, let me know!

**Comment by tmcqueen-materials** [comment]
@eminizer : Thanks for cleaning this up. kafka-python shouldn't be needed as a dependency for KafkaCrypto (as long as confluent-kafka is installed), but maybe some of the tests require it? Just couch surfing so to speak -- let me know if you need anything. Thanks!

**Comment by tmcqueen-materials** [comment]
@eminizer The current CI errors (which look like from mine) come from the fact that ssl_cafile in the kafkacrypto config file rewrites ssl.ca.location . But it is not as simple as removing it, since KafkaCryptoStore needs to make sure it is there if it isn't given (see https://github.com/tmcqueen-materials/kafkacrypto/blob/9d0ea92196b7d61b9442707a3218eccebf3a2d81/kafkacrypto/kafkacryptostore.py#L40 ). So the proper fix I think is to make sure ssl_cafile in the kafkacrypto config is set to the same thing as the main OpenMSI config. Or to adjust the load a little bit to remove ssl_cafile from what KafkaCryptoStore returns.

**Comment by eminizer** [comment]
@tmcqueen-materials yes, kafka-python is actually needed by OpenMSIStream to reset consumer offsets on startup, and I had never made that explicit until now since it was coming along with kafkacrypto. I've added it as a dependency now and I'm just working on a reliable fix for the cert file. Should be all set soon. Thank you again!

**Comment by eminizer** [comment]
@tmcqueen-materials sorry, just saw your second comment. The main config doesn't explicitly set the ssl.ca.location unless the user has added that to the config file : / I'll need to edit this workflow a little more, in that case, I didn't realize

**Comment by tmcqueen-materials** [comment]
@eminizer : It occurs to me you might want a note about needing to check that things work as expected when updating to this version, since this is the first version actually reading all the kafkacrypto config file contents "in full".

**Comment by eminizer** [comment]
> @eminizer : It occurs to me you might want a note about needing to check that things work as expected when updating to this version, since this is the first version actually reading all the kafkacrypto config file contents "in full".

I'll make a note of it in the new release in just a moment.

In other news, it looks like just removing the ssl_cafile value from the testing KafkaCrypto config files works alright, and I added a new block to the config file parser that will pass along any ssl.ca.location value from the main config to the KafkaCrypto config file. I think that handles this issue as best as possible, as you had suggested.

**Pull request merged**
