### PR TITLE
Fix TypeError in S3TransferStreamProcessor

### PR DESCRIPTION
**Pull request by haochenpan**
Hello,

I am currently exploring OpenMSIStream to understand its capabilities better and explore potential collaboration opportunities with our Octopus Event Fabric (referenced on [arXiv](https://arxiv.org/abs/2407.11432) and [GitHub](https://github.com/globus-labs/diaspora-event-sdk/tree/main)). While running the `S3TransferStreamProcessor` on my Mac, I encountered an error when pressing `q`:

```bash
[S3TransferStreamProcessor 2024-09-21 22:49:32] 6 total messages were consumed, 6 messages were successfully processed, and 6 files were transferred to the openmsistream-octopus-tryout bucket
Traceback (most recent call last):
  File "/opt/anaconda3/envs/openmsi/bin/S3TransferStreamProcessor", line 8, in <module>
    sys.exit(main())
  File "/Users/haochen/Downloads/openmsistream/openmsistream/s3_buckets/s3_transfer_stream_processor.py", line 165, in main
    S3TransferStreamProcessor.run_from_command_line(args)
  File "/Users/haochen/Downloads/openmsistream/openmsistream/s3_buckets/s3_transfer_stream_processor.py", line 145, in run_from_command_line
    msg += "\n\t".join(complete_filenames)
TypeError: sequence item 0: expected str instance, PosixPath found
```

The issue seems to be caused by the `complete_filenames` list containing `PosixPath` objects instead of strings on MacOS. This one-line fix converts each `PosixPath` to a string before joining filenames.

After the fix (and adjust the warning level locally), I was able to get:
```bash
[S3TransferStreamProcessor 2024-09-21 22:53:01] WARNING: 6 files were successfully transferred to the openmsistream-octopus-tryout bucket.
Transferred filepaths (up to 50 most recent):
        group1/SC006 XRR.csv
        group2/SC001 XRR.csv
        group2/SC002 XRR.csv
        group1/SC007 XRR.csv
        group2/SC003 XRR.csv
        group1/SC009 XRR.csv
```
I noticed that you have a CircleCI pipeline, but I am unfamiliar with how CI/CD workflows are set up for external contributors. Locally, I changed the version to `1.8.1` and ran `python test/run_all_tests.py --no_pylint --no_kafka --failfast`, which resulted in all tests passing. However, I am unsure if there are additional tests or processes I should follow to validate my changes further.

Thank you for reviewing my PR, and please let me know if any additional steps are required or if any feedback is needed.

Best regards,  
Haochen Pan

### CODE REVIEW

**Comment by haochenpan** [comment]
After submitting the PR, I noticed that this repository has CircleCI checks in place, but the PR failed due to the version tag issue. Please let me know if I should submit another commit to update the version tag to 1.8.1. Thank you!

**Comment by davidelbert** [comment]
Hi Haochen. Thanks for bringing this up. Could you please make a branch and put your fix there so I can review it? We can then fix or add a unit test and I'll run the CI/CD tests.  Thank you.

**Comment by haochenpan** [comment]
Hi David,

Thank you for your quick response! Since I don't have write access to the main repository (`openmsi:openmsistream`), I forked it and made my changes in my fork (`haochenpan:openmsistream`). You can review my changes in this pull request [here](https://github.com/openmsi/openmsistream/pull/64/files).

I noticed that the CircleCI checks for this pull request did not pass, which might be due to an issue with the test environment setup: [CircleCI Job Link](https://app.circleci.com/pipelines/github/openmsi/openmsistream/638/workflows/4552a409-33f4-4574-af35-831cb71954f1/jobs/1596). 

Please let me know if there's anything else I should adjust. Thank you!

Best regards,  
Haochen

CircleCI Test Failure Screenshot

**Comment by eminizer** [comment]
Hi Haochen and David,

Sorry for the late reply to this thread; I've been on vacation for the past two weeks but am now back at work.

Thank you for finding this bug, and my apologies for it. As you point out, it's a very simple fix, and the other good news is that it doesn't affect the behavior of S3TransferStreamProcessor-type programs beyond crashing trying to log this message when they are shut down (oops).

Our CI pipeline depends on some secrets stored in the CircleCI system that are restricted to only be available in runs coming from the main repo, which is why you're seeing the tests fail. I've just created a new branch and merged the commits with your one line fix plus the version updates, and I'll merge a pull request with those updates in it in just a moment (looks like the tests are passing). The new version of OpenMSIStream (v1.8.1) should be available on PyPI shortly thereafter.

It looks like this PR includes some extra commits for using Octopus, so I'm going to close this PR when the other one is merged and you should be able to continue your work in your fork.

Thanks again for reaching out and please let us know if you run into anything else or need any more help.

**Comment by haochenpan** [comment]
Thanks, please close this PR! I did not realize that the Octopus-related code is also tracked by this PR!

**Comment by eminizer** [comment]
As promised, this fix was implemented by merging PR #65 and is a part of [release v1.8.1](https://github.com/openmsi/openmsistream/releases/tag/v1.8.1). The new version is now available [on PyPI](https://pypi.org/project/openmsistream/1.8.1/).

Thank you again for your help!

**Comment by davidelbert** [comment]
Thanks Maggie!   I was working on finding time to get the CI pipeline to run to merge that but am glad you could knock it out.

-David




From: Maggie Eminizer ***@***.***>
Date: Monday, September 30, 2024 at 1:18 PM
To: openmsi/openmsistream ***@***.***>
Cc: David Elbert ***@***.***>, Comment ***@***.***>
Subject: Re: [openmsi/openmsistream] Fix TypeError in S3TransferStreamProcessor (PR #64)

Hi Haochen and David,

Sorry for the late reply to this thread; I've been on vacation for the past two weeks but am now back at work.

Thank you for finding this bug, and my apologies for it. As you point out, it's a very simple fix, and the other good news is that it doesn't affect the behavior of S3TransferStreamProcessor-type programs beyond crashing trying to log this message when they are shut down (oops).

Our CI pipeline depends on some secrets stored in the CircleCI system that are restricted to only be available in runs coming from the main repo, which is why you're seeing the tests fail. I've just created a new branch and merged the commits with your one line fix plus the version updates, and I'll merge a pull request with those updates in it in just a moment (looks like the tests are passing). The new version of OpenMSIStream (v1.8.1) should be available on PyPI shortly thereafter.

It looks like this PR includes some extra commits for using Octopus, so I'm going to close this PR when the other one is merged and you should be able to continue your work in your fork.

Thanks again for reaching out and please let us know if you run into anything else or need any more help.

**Pull request closed without merging**
