### PR TITLE
Use matrix for running tests with different Python versions

### PR DESCRIPTION
**Pull request by Xarthisius**
Bumps `python_requires` to latest supported version (3.11) on one end, and tests to the oldest not-yet-EOL version of py on the other end. Py3.12 is not supported by some kafka's deps yet.

### CODE REVIEW

**Comment by eminizer** [comment]
We've worked to maintain Python 3.7 support to this point because some older versions of Windows don't support newer Python versions, and we've run into a few lab computers running those older Windows versions that either won't or can't be upgraded (for better or for worse [read: for worse]).

I don't see 3.7 listed in the matrix you've added (which, clever and thank you), but if y'all would like to drop support for it that's a consideration, I think.

Also I dunno if you'll be able to get the CI tests to run from a fork of the repo. Let me know if I can help out with, like, any of this. Feel free to email me as well.

**Comment by Xarthisius** [comment]
> We've worked to maintain Python 3.7 support to this point because some older versions of Windows don't support newer Python versions, and we've run into a few lab computers running those older Windows versions that either won't or can't be upgraded (for better or for worse [read: for worse]).

I wasn't aware, re-added.

> Also I dunno if you'll be able to get the CI tests to run from a fork of the repo. Let me know if I can help out with, like, any of this. Feel free to email me as well.

It's a bit magical that it runs on my fork instead of on a merge head here (which I thought is default behavior). I set up S3 bucket, let's see if it works. I will bill @davidelbert for all costs incurred... ;-)

**Comment by Xarthisius** [comment]
@eminizer could you explain that last test a bit? Why would running tests result in modifications to git repo? In the meantime I'll try to figure out how to do that for 3 concurrent jobs.

**Comment by davidelbert** [comment]
> We've worked to maintain Python 3.7 support to this point because some older versions of Windows don't support newer Python versions, and we've run into a few lab computers running those older Windows versions that either won't or can't be upgraded (for better or for worse [read: for worse]).

I'll interject that Python 3.8 from python.org runs on Windows 7, but this whole issue of compatibility with old Windows is enough of a pain that I think as a general policy we should support Python 3.7 until we have a feature that needs something only available in the more recent versions.

**Comment by eminizer** [comment]
> @eminizer could you explain that last test a bit? Why would running tests result in modifications to git repo? In the meantime I'll try to figure out how to do that for 3 concurrent jobs.

running the tests certainly shouldn't result in modifications to the repo, hence the check. The tests are just moving and copying a lot of files places so I added a check to make sure that the tests are truly self-contained.

Feel free to get rid of it if it's causing any problems. I may also be forgetting something from a long time ago but I don't think I am.

**Comment by Xarthisius** [comment]
I tried to be clever and run it conditionally and only once, but then I threw my hands up and thought: why not simply run it N times if it takes less than 1sec. Fingers crossed for all green!

**Comment by davidelbert** [comment]
Is it still the  test_repo_status script causing trouble?   git status --porcelain can be pretty finicky even with whitespace

**Comment by Xarthisius** [comment]
> Is it still the test_repo_status script causing trouble? git status --porcelain can be pretty finicky even with whitespace

It's fine. Doing a merge of workspaces was causing issues, but I figured it out.

**Review by arachid1 — COMMENTED** [review]
All required checks have successfully passed after updating the branch protection settings to align with the latest configuration. `check-repo` and `run-tests` checks were removed from the required list as they are no longer relevant to the current branch setup.

1) Should we expand the matrix tests to include Python versions 3.8 and 3.10?
2) Do we have a standard method for capturing the diff output generated by Black during tests? I believe the default behavior is that diffs are printed to CLI. 
This diff could be useful for developers as a reference for local reformatting. For example, we might consider storing the diff output in a log file (i.e., `black openmsistream --check --diff > build/openmsistream_diff_output.txt`) or making it accessible as an artifact to streamline the formatting correction process.

**Comment by Xarthisius** [comment]
> All required checks have successfully passed after updating the branch protection settings to align with the latest configuration. `check-repo` and `run-tests` checks were removed from the required list as they are no longer relevant to the current branch setup.
> 
> 1. Should we expand the matrix tests to include Python versions 3.8 and 3.10?

I think that's unnecessary. Oldest and latest should be enough.

> 2. Do we have a standard method for capturing the diff output generated by Black during tests? I believe the default behavior is that diffs are printed to CLI.

I don't think we want to preserve that output. I only added it cause there were subtle differences in environments between CI and my dev box, and I wanted to see what's going on. I kept it cause it's generally useful.

>    This diff could be useful for developers as a reference for local reformatting. For example, we might consider storing the diff output in a log file (i.e., `black openmsistream --check --diff > build/openmsistream_diff_output.txt`) or making it accessible as an artifact to streamline the formatting correction process.

**Comment by davidelbert** [comment]
Everything has passed so time to merge.

**Pull request merged**
